//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mantenimiento_proyecto.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mantenimiento_proyecto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD
        ///XHTML 1.0 Transitional//EN&quot;
        ///          &quot;http://www.w3.org/TR/xhtml1/DTD/
        ///xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;&lt;/meta&gt;
        ///
        ///    &lt;title&gt;listaVerificacion1&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .c1 
        ///        {
        ///           width: 20%; 
        ///        }
        ///        .tablaEncabezado 
        ///        {
        ///            margin-left: 5%;
        ///            width: 96%;
        ///            height: 27%;
        ///            border-bottom: darkred solid 2.5px;
        ///            border-top: darkred [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EncabezadoLista {
            get {
                return ResourceManager.GetString("EncabezadoLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD
        ///XHTML 1.0 Transitional//EN&quot;
        ///          &quot;http://www.w3.org/TR/xhtml1/DTD/
        ///xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;&lt;/meta&gt;
        ///
        ///    &lt;title&gt;ProgramaAnual&lt;/title&gt;
        ///    &lt;style&gt;
        ///         .celda1 {
        ///            border: 0.1px black solid;
        ///            border-collapse: collapse;
        ///            padding: 3%;
        ///            font-size: 70%;
        ///        }
        ///
        ///        .celda3 {
        ///            border: 0.1px black solid;
        ///            border-collapse: collapse;
        ///         [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string encabezadoPrograma {
            get {
                return ResourceManager.GetString("encabezadoPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo4 {
            get {
                object obj = ResourceManager.GetObject("logo4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoITM {
            get {
                object obj = ResourceManager.GetObject("logoITM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoTecNM {
            get {
                object obj = ResourceManager.GetObject("logoTecNM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD
        ///XHTML 1.0 Transitional//EN&quot;
        ///          &quot;http://www.w3.org/TR/xhtml1/DTD/
        ///xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;&lt;/meta&gt;
        ///
        ///    &lt;title&gt;listaVerificacion1&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .c1 {
        ///            margin-top: 10%;
        ///            margin-left: 10%;
        ///        }
        ///
        ///        .tabla1 {
        ///            width: 94%;
        ///            border: 0.2px black solid;
        ///            border-collapse: collapse;
        ///        }
        ///
        ///        .celda1 {
        ///            bor [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string pieLista {
            get {
                return ResourceManager.GetString("pieLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD
        ///XHTML 1.0 Transitional//EN&quot;
        ///          &quot;http://www.w3.org/TR/xhtml1/DTD/
        ///xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;&lt;/meta&gt;
        ///
        ///    &lt;title&gt;programaAnual&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;br /&gt;
        ///    &lt;br /&gt;
        ///    &lt;div&gt;
        ///        &lt;b&gt;
        ///            &lt;p&gt;FECHA DE ELABORACIÓN: &lt;u&gt; @fecha &lt;/u&gt;       
        ///                &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;
        ///                &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;
        ///                &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;
        ///                ELABORÓ:&lt;u&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string piePrograma {
            get {
                return ResourceManager.GetString("piePrograma", resourceCulture);
            }
        }
    }
}
